name:                intensional-constraints
version:             0.1.0.0
github:              "eddiejones2108/intensional-constraints"
license:             BSD3
author:              "Eddie Jones"
maintainer:          "ej16147@bristol.ac.uk"
copyright:           "2019 Eddie Jones"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eddiejones2108/intensional-constraints#readme>

dependencies:
- base >= 4.7
- ghc
- containers
- mtl
- parsec

library:
  source-dirs: src

tests:
  intensional-constraints-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin Lib
    dependencies:
    - intensional-constraints
